apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: app.paas.company.io
spec:
  group: paas.company.io
  names:
    kind: App
    plural: app
  claimNames:
    kind: AppClaim
    plural: appclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              serviceId:
                type: string
              replicas:
                type: integer
              image:
                type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: app.paas.company.io
  labels:
    provider: upbound
spec:
  compositeTypeRef:
    apiVersion: paas.company.io/v1alpha1
    kind: App
  patchSets:
    - name: patch-namespace
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "serviceId"
        toFieldPath: "metadata.namespace"
  resources:
    - name: namespace
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
          providerConfigRef:
            name: provider-kubernetes
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.serviceId
          toFieldPath: spec.forProvider.manifest.metadata.name
    - name: deployment
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: apps/v1
              kind: Deployment
              spec:
                selector:
                  matchLabels:
                    app: app
                template:
                  metadata:
                    labels:
                      app: app
                  spec:
                    containers:
                      - name: app-container
          providerConfigRef:
            name: provider-kubernetes
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.serviceId
          toFieldPath: spec.forProvider.manifest.metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.serviceId
          toFieldPath: spec.forProvider.manifest.metadata.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.replicas
          toFieldPath: spec.forProvider.manifest.spec.replicas
        - type: FromCompositeFieldPath
          fromFieldPath: spec.image
          toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].image
    - name: service
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Service
              spec:
                selector:
                  app: app
                ports:
                  - port: 80
                    targetPort: 8080
          providerConfigRef:
            name: provider-kubernetes
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.serviceId
          toFieldPath: spec.forProvider.manifest.metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.serviceId
          toFieldPath: spec.forProvider.manifest.metadata.namespace
